### ISSUE TITLE
Generate Error in Cmake

### ISSUE THREAD

**Issue by Enigma-li** [NSchertler/OnlineSurfaceReconstruction#1]
Hi,

Thanks for your great work, and I am trying to test the code. One problem is that when I compile it using Cmake in window 10, 64-bit VS 2015, the configuration goes smoothly but when I press generate button, there are error like:
CMake Error at CMakeLists.txt:236 (add_executable):
  Cannot find source file:

    include/Attributes.h

I checked the file system, the Attributes.h lies in include/osr folder, maybe there are error in CMakeLists line 236. Am I right?

Thanks

**Comment by NSchertler** [comment]
Hi,
Thanks for letting me know. I performed this restructuring yesterday. And apparently, I did not commit every change due to some local Git problems. But that should be resolved now. Can you verify?
Nico

**Comment by Enigma-li** [comment]
Thanks, it works for me now.

Changjian
