### ISSUE TITLE
Linking Error for libOSR.dylib

### ISSUE THREAD

**Issue by kylelo** [NSchertler/OnlineSurfaceReconstruction#10]
Hi,

I was trying to compile source code on macOS (10.15.1) with the command-line tool Xcode (10.2.1).
I followed the instruction in README without any problem for cmake:
![Screen Shot 2019-12-16 at 11 38 35 PM](https://user-images.githubusercontent.com/7735800/70965893-3f0cb200-205f-11ea-8df4-e8b303f3cf40.png)

However, I faced linking error during compilation:
![Screen Shot 2019-12-16 at 11 54 57 PM](https://user-images.githubusercontent.com/7735800/70966025-b5111900-205f-11ea-9acb-86b9e0124d7c.png)

I thought the error is caused by the fact that clang doesn't support OpenMP so I tried
```
cmake .. -DNANOGUI_USE_GLAD=ON -WITH_OPENMP=OFF
```
but the error remained the same...

Any help would be appreciated!

**Comment by NSchertler** [comment]
The OpenMP dependency is added [here](https://github.com/NSchertler/OnlineSurfaceReconstruction/blob/master/libOSR/CMakeLists.txt#L105). It should check if OpenMP is there. You seem to have some form of OpenMP support there, but apparently it is not working correctly. Can you try to comment out the according lines in the `CMakeLists.txt`? And make sure that no OpenMP support is activated in your compiler.

**Comment by kylelo** [comment]
It works after commended out
```
find_package(OpenMP)
if(OPENMP_FOUND)
  add_definitions(-DOPENMP)
  set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${OpenMP_C_FLAGS}")
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${OpenMP_CXX_FLAGS}")
  set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${OpenMP_EXE_LINKER_FLAGS}")
endif()
```
Thanks for your help!
