### ISSUE TITLE
[MacOS] OpenGL 430 not supported 

### ISSUE THREAD

**Issue by stephane-lb** [NSchertler/OnlineSurfaceReconstruction#2]
Hi,

First of all, thanks for your amazing work!

Just to let you know even if the compilation succeed on my Mac, the program is calling openGL 430 which is (sadly) not available on Mac. 

Except if you have a solution to bypass this, I don't think your app will be available on Mac.

Best Regards,

Stephane-lb

**Comment by NSchertler** [comment]
Thanks for letting me know. I already have a fallback renderer implemented locally, which should also resolve this problem. I still need to test it on another machine before I upload it. This will happen in the next two weeks. I will let you know.

**Comment by NSchertler** [comment]
I uploaded the fallback renderer (a2451bccc07ac81d8e6105e839041c4c81ce15a3). Can you verify if it works on Mac?

**Comment by stephane-lb** [comment]
Hi Nicolas,

Thanks for considering maintaining cross platform development ! 
I got a compilation error: 
```
/Users/stephane-lb/Projects/OnlineSurfaceReconstruction/src/osr/gui/GLBuffer.cpp:21:76: error: use of undeclared identifier 'GL_SHADER_STORAGE_BUFFER'
const GLuint BufferTargets[] = { GL_ARRAY_BUFFER, GL_ELEMENT_ARRAY_BUFFER, GL_SHADER_STORAGE_BUFFER };
                                                                           ^
```
Sadly, this is not supported by OpenGL on OSX. I just removed it from the enum and it compiled.

However, at execution I got this : 
```
Error: 
ERROR: 0:1: '' :  version '430' is not supported
ERROR: 0:2: '' :  #version required and missing.
ERROR: 0:21: ';' : syntax error: Uniform blocks may not have identifiers in GLSL 140
```

So unfortunately, your fix did not solve the problem. Is there a way to force the soft to use your fallback renderer ?

Best Regards,

Stephane-lb

**Comment by NSchertler** [comment]
Let's try this once more. There were some shaders left that had the 430 version. All of them should have 330 now except for the ones that need it (and these won't be compiled on a context that doesn't support it).
The compiler error is probably caused because you use GLFW. If you switch to GLAD (turn on NANOGUI_USE_GLAD like in the example build command line), this should be resolved.

**Comment by stephane-lb** [comment]
Ok that's better, one more errors. I just did a fresh clone and rebuild.

```glsl
// Error while compiling geometry shader "FlatMeshShader":
#version 330 compatibility

/*
	This file is part of the implementation for the technical paper

		Field-Aligned Online Surface Reconstruction
		Nico Schertler, Marco Tarini, Wenzel Jakob, Misha Kazhdan, Stefan Gumhold, Daniele Panozzo
		ACM TOG 36, 4, July 2017 (Proceedings of SIGGRAPH 2017)

	Use of this source code is granted via a BSD-style license, which can be found
	in License.txt in the repository root.

	@author Nico Schertler
*/

layout(triangles) in;
layout(triangle_strip, max_vertices = 3) out;

in GEOM_IN
{
	vec4 pos;
	vec4 color;	
} vIn[];

out FRAG_IN
{
	vec4 pos;
	vec4 color;	
	vec3 n;
} vOut;

void main(void)
{
	vOut.n = normalize(cross(vIn[1].pos.xyz - vIn[0].pos.xyz, vIn[2].pos.xyz - vIn[0].pos.xyz));
	for(int i = 0; i < 3; ++i)
	{
		vOut.pos = vIn[i].pos;
		vOut.color = vIn[i].color;
		gl_Position = gl_in[i].gl_Position;
		EmitVertex();
	}
}

Error: 
ERROR: 0:1: '' : syntax error: #version
```

I made some test and it looks like Mac doesn't like : "#version 330 compatibility" and prefer "#version 330" ... I will continue the investigation. ;-)

**Comment by NSchertler** [comment]
Does `#version 330` work? That would be an easy fix.

**Comment by stephane-lb** [comment]
Yes ```#version 330``` works. Will patch all the shaders soon.

**Comment by stephane-lb** [comment]
I confirm that ```sed -i -- 's/version 330 compatibility/version 330/g'``` allowed me to launch the app. Obviously just got the widget to say that some of the features would not be available. 

I will make some test and I will write here if everything fine. 

Thanks for your help.

**Comment by stephane-lb** [comment]
If needed binary available here : https://drive.google.com/open?id=0B4OKayijuI7xNC1hVWVVMC1MeGc
