### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by ghost** [NSchertler/OnlineSurfaceReconstruction#3]
Sorry to use issues to reach out to you but thank you for sharing this research on GitHub!  It's always fantastic to see open source in graphics, especially in such cutting edge research.

Congratulations on the SIGGRAPH paper, best of luck!

**Comment by NathanBWaters** [comment]
You did an incredible job on the presentation and I can't wait to try out this tool!

**Comment by NSchertler** [comment]
Thanks a lot. Really appreciate the feedback.
