### ISSUE TITLE
David scanner

### ISSUE THREAD

**Issue by nosleduc** [NSchertler/OnlineSurfaceReconstruction#4]
Hi

Does your application require using a scanner from David scanner  because I don't see code to make 3D point clouds ?

**Comment by NSchertler** [comment]
Hi, the application does not include code to produce point clouds. You either need to load files or add a scanner-specific ScanLoader (https://github.com/NSchertler/OnlineSurfaceReconstruction/wiki/ScanLoader). There is a ScanLoader for a David scanner in combination with a Vive controller, but this code is not yet very generalized (meaning it is tailored to the software and hardware setup of the machine I used).
